config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# post 'create_ticket', to: 'application#create_ticket'
# get 'ticket/:id', to: 'application#show_ticket'
# get 'tickets', to: 'application#show_tickets'


namespace :api, defaults: { format: :json } do
  namespace :v1 do
  	resource :tickets, only: %i(create) do
  	  get  :show_tickets, on: :collection
      get 'ticket/:id', to: 'tickets#show_ticket', on: :collection
    end
  end
end

resources :tickets, only: %i(index show destroy)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/excavator.rb
class Excavator < ApplicationRecord
  belongs_to :ticket
  validates :company_name, presence: true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_one :excavator , dependent: :destroy

  validates :request_number, presence: true
  validates :request_type, presence: true
  serialize :additional_sa_code

  def self.create_ticket(ticket_params, excavator_params)
    ActiveRecord::Base.transaction do
      ticket = self.new(ticket_params)
      ticket.save!
      excavator = Excavator.new(excavator_params.merge(ticket: ticket))
      return  [true, ticket, nil] if excavator.save!(excavator_params)
    end
    rescue ActiveRecord::RecordInvalid => ex
    [false, nil, ex.message.split(': ').drop(1) ]
  end

  def self.convert_polygon(polygon)
    polygon.gsub('POLYGON((', '').gsub('))', '').gsub(' ',',-').split(',').map(&:to_f).each_slice(2).to_a
  end
end

app/controllers/api/base_controller.rb
class API::BaseController < ActionController::API

  protected
  def index_json(objects)
    objects.map do |object|
      individual_json(object)
	  end
  end

  def individual_json(object)
    { ticket: json_object(object), excavator: json_object(object.excavator) }
  end

  def json_object(object)
	  object.as_json.except('updated_at', 'created_at')
  end
end

app/controllers/api/v1/tickets_controller.rb
class Api::V1::TicketsController < API::BaseController

  # POST /api/v1/tickets, Log A Ticket
  def create
    status, object, errors = Ticket.create_ticket(ticket_params,excavator_params)
    if status
      render json: individual_json(object).merge(message: 'Saved Successfully..!',), status: :created
    else
      render json: {message: 'Could not able to create with the given params', errors: errors}, status: :unprocessable_entity
    end
  end

  # GET /api/v1/tickets/ticket/:id, Get A Ticket based on Id
  def show_ticket
    ticket  = Ticket.includes(:excavator).find_by(id: params[:id])
    if ticket.present?
      render json: individual_json(ticket)
    else
      render json: {message: 'Record Not Found'}, status: :not_found
    end  
  end

  # GET /api/v1/tickets/show_tickets, Get All Tickets
  def show_tickets
    tickets = Ticket.includes(:excavator).all
    if tickets.present?
      render json: index_json(tickets)
    else
      render json: {message: 'Records Not Found'}, status: :not_found
    end
  end

  private

  def ticket_params
    {
      request_number: params[:RequestNumber],
      sequence_number: params[:SequenceNumber],
      request_type: params[:RequestType],
      primary_sa_code: params.dig(:ServiceArea, :PrimaryServiceAreaCode, :SACode),
      additional_sa_code: params.dig(:ServiceArea, :AdditionalServiceAreaCodes, :SACode),
      digi_site_info: params.dig(:ExcavationInfo, :DigsiteInfo, :WellKnownText),  
      due_date_time: params.dig(:DateTimes, :ResponseDueDateTime)
    }
  end

  def excavator_params
    {
      company_name: params.dig(:Excavator, :CompanyName),
      address: params.dig(:Excavator,:Address),
      city: params.dig(:Excavator, :City),
      state: params.dig(:Excavator, :State),
      zip_code: params.dig(:Excavator, :Zip),
      crew_on_site: params.dig(:Excavator, :CrewOnsite).to_s == 'true'
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  # GET /tickets, Get All Tickets
  def index
    @tickets = Ticket.includes(:excavator).all
  end

  # GET /tickets/:id, Get A Ticket based on Id
  def show
    @ticket = Ticket.includes(:excavator).find(params[:id])
    @polygon = Ticket.convert_polygon(@ticket.digi_site_info)
  end
end

app/views/tickets/index.html.erb
<!doctype html>
<html lang="en">
  <head>

<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <style type="text/css">
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd !important;
  text-align: left;
  padding: 8px;
}
  </style>
 </head>
 <body>
<h1>Tickets</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Request Number</th>
      <th>Sequence Number</th>
      <th>Request Type</th>
      <th>Primary SA Code</th>
      <th>Additional SA Code</th>
      <th>Show List</th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.id %></td>
        <td><%= ticket.request_number %></td>
        <td><%= ticket.sequence_number %></td>
        <td><%= ticket.request_type %></td>
        <td><%= ticket.primary_sa_code %></td>
        <td><%= ticket.additional_sa_code %></td>
        <td><%= link_to 'Show', ticket %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</body>
</html>

app/views/tickets/show.html.erb
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://hpneo.dev/gmaps/prettify/prettify.css">
<link rel="stylesheet" href="https://hpneo.dev/gmaps/examples/examples.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<script src="https://maps.google.com/maps/api/js?sensor=true"></script>
<script src="https://hpneo.dev/gmaps/gmaps.js"></script>
<script src="https://hpneo.dev/gmaps/prettify/prettify.js"></script>
<style type="text/css">
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd !important;
  text-align: left;
  padding: 8px;
}
#map{
	height: 400px;
	position: relative;
	overflow: hidden;
}

</style>
</head>
<body>
<h1>Ticket Detail</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Request Number</th>
      <th>Sequence Number</th>
      <th>Request Type</th>
      <th>Primary SA Code</th>
      <th>Additional SA Code</th>
      <th>Company Name</th>
      <th>City</th>
      <th>State</th>
      <th>Zip Code</th>
      <th>Crew</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
     <tr>
        <td><%= @ticket.id%></td>
        <td><%= @ticket.request_number %></td>
        <td><%= @ticket.sequence_number %></td>
        <td><%= @ticket.request_type %></td>
        <td><%= @ticket.primary_sa_code %></td>
        <td><%= @ticket.additional_sa_code %></td>
        <td><%= @ticket.excavator.company_name%></td>
        <td><%= @ticket.excavator.city%></td>
        <td><%= @ticket.excavator.state%></td>
        <td><%= @ticket.excavator.zip_code%></td>
        <td><%= @ticket.excavator.crew_on_site%></td>
      </tr> 
  </tbody>
</table>

<div id="map"></div>

<%= link_to 'Back', tickets_path %>

<script type="text/javascript">
  var map;
  $(document).ready(function(){
    map = new GMaps({
      div: '#map',
      lat: -81.133902,
      lng: -32.072069
  });

  var path = <%= @polygon %>;

  polygon = map.drawPolygon({
	  paths: path,
	  strokeColor: '#BBD8E9',
	  strokeOpacity: 1,
	  strokeWeight: 3,
	  fillColor: '#BBD8E9',
	  fillOpacity: 0.6
	});
});
</script>
<br>
</body>
</html>